### ISSUE TITLE
Add saving results to file

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [techspence/BadShares#3]
Either automatically save the displayed BadShare results in a file like `BadShare-Results.txt` in the local directory, or allow an optional parameter to save the results directly to a file.

Useful to automatically save the results without having to copy/paste the results manually or parse the output of the script.

**Comment by techspence** [comment]
Great idea @Marshall-Hallenbeck, thank you. I will work on adding this in.

**Comment by techspence** [comment]
This has been added with https://github.com/techspence/BadShares/commit/5029e095006bdb57c54be39ab9b67a8165a3b63c. I use the PowerShell transcript. Thanks again for the recommendation!
